# Generated by Django 3.0.5 on 2020-05-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='openid',
        ),
    ]
