# Generated by Django 3.0.5 on 2020-05-20 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20200520_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('intro', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('intro', models.CharField(max_length=500)),
                ('lessons', models.ManyToManyField(to='myblog.Lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Recommends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=30)),
                ('cover', models.ImageField(upload_to='img')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=200)),
                ('recommend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Recommends')),
            ],
        ),
        migrations.CreateModel(
            name='Colletions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('recommend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Recommends')),
            ],
        ),
    ]
