# Generated by Django 3.0.5 on 2020-05-21 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_colletions_comments_lessons_recommends_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='recommend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myblog.Recommends'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lessons',
            field=models.ManyToManyField(related_name='lessons', to='myblog.Lessons'),
        ),
    ]
