# Generated by Django 3.0.5 on 2020-05-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20200521_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommends',
            name='cover',
        ),
        migrations.AddField(
            model_name='recommends',
            name='cover1',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='recommends',
            name='cover2',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='recommends',
            name='cover3',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
