# Generated by Django 3.0.5 on 2020-05-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_auto_20200521_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colletions',
            name='recommend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colletions', to='myblog.Recommends'),
        ),
        migrations.AlterField(
            model_name='recommends',
            name='cover1',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='recommends',
            name='cover2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='recommends',
            name='cover3',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
