# Generated by Django 3.0.5 on 2020-05-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_auto_20200521_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommends',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
