# Generated by Django 3.0.5 on 2020-06-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_recommends_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommends',
            name='col_count',
            field=models.IntegerField(default=0),
        ),
    ]
